//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDeAula_SaraPineda_EmanuelGallego.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbFactura
    {
        public int IdFactura { get; set; }
        public int IdAgua { get; set; }
        public int IdEnergia { get; set; }
        public int IdPrecios { get; set; }
        public decimal PagoAgua { get; set; }
        public decimal PagoEnergia { get; set; }
        public decimal PagoTotal { get; set; }
    
        public virtual tbAgua tbAgua { get; set; }
        public virtual tbEnergia tbEnergia { get; set; }
        public virtual tbPrecios tbPrecios { get; set; }
    }
}
